[package]
name = "rust_mining_ex"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-hash = "0.3.4"
# TODO histogram = "0.11.1"
histogram = "0.6.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
